/// <reference lib="dom" />
import React, { useState } from 'react';
import { GoogleGenAI } from "@google/genai";
import { FileUploader } from '../../components/FileUploader';
import { Button } from '../../components/ui/Button';
import { ApiKeyInput } from '../../components/ui/ApiKeyInput';
import { FileData } from '../../types';
import { Wand2, Download, RefreshCcw, Sliders, Sparkles, AlertCircle } from 'lucide-react';

import { useIsMobile } from '../../hooks/useIsMobile';

export const MagicImageEditor: React.FC = () => {
  const isMobile = useIsMobile();
  const [file, setFile] = useState<FileData | null>(null);
  const [prompt, setPrompt] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);
  const [resultImage, setResultImage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [sliderPosition, setSliderPosition] = useState(50);
  const [apiKey, setApiKey] = useState('');

  const handleReset = () => {
    setFile(null);
    setPrompt('');
    setResultImage(null);
    setError(null);
    setIsProcessing(false);
  };

  const getBase64 = (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => {
        if (typeof reader.result === 'string') {
          resolve(reader.result.split(',')[1]);
        } else {
          reject(new Error("Failed to read file"));
        }
      };
      reader.onerror = reject;
    });
  };

  const handleGenerate = async () => {
    if (!file || !prompt) return;

    setIsProcessing(true);
    setError(null);

    try {
      if (!apiKey) throw new Error("Please enter your Gemini API Key first");

      const base64Data = await getBase64(file.file);
      const ai = new GoogleGenAI({ apiKey });

      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [
            {
              inlineData: {
                data: base64Data,
                mimeType: file.file.type,
              },
            },
            {
              text: prompt,
            },
          ],
        },
      });

      // Extract image from response
      let foundImage = false;
      if (response.candidates && response.candidates[0].content && response.candidates[0].content.parts) {
        for (const part of response.candidates[0].content.parts) {
          if (part.inlineData) {
            const base64EncodeString = part.inlineData.data;
            const imageUrl = `data:image/png;base64,${base64EncodeString}`;
            setResultImage(imageUrl);
            foundImage = true;
            break;
          }
        }
      }

      if (!foundImage) {
        throw new Error("No image generated by the model. Try a different prompt.");
      }

    } catch (err) {
      console.error(err);
      let message = (err as Error).message || "An error occurred while generating the image.";

      // Parse detailed AI errors
      if (message.includes('429') || message.toLowerCase().includes('quota')) {
        message = "Usage limit exceeded. Please try again later or check your API quota.";
      } else if (message.includes('401') || message.toLowerCase().includes('key')) {
        message = "Invalid API Key. Please verify your credentials.";
      } else if (message.includes('{')) {
        try {
          // Attempt to extract friendly message from JSON blob
          const jsonMatch = message.match(/\{[\s\S]*\}/);
          if (jsonMatch) {
            const errorObj = JSON.parse(jsonMatch[0]);
            if (errorObj.error && errorObj.error.message) {
              message = errorObj.error.message;
            }
          }
        } catch (e) { /* use original message */ }
      }

      setError(message);
    } finally {
      setIsProcessing(false);
    }
  };

  if (!file) {
    return (
      <div className="max-w-3xl mx-auto space-y-8 animate-fade-in">
        <div className="text-center space-y-2">
          <h2 className="text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-pink-500">
            Magic Image Editor
          </h2>
          <p className="text-zinc-400">Edit images using natural language prompts powered by Gemini 2.5.</p>
        </div>
        <div className="p-8 bg-surface rounded-3xl shadow-xl shadow-purple-500/5 border border-zinc-800/50">
          <FileUploader
            onFileSelect={setFile}
            accept="image/*"
            label="Upload Image to Edit"
            description="JPG, PNG, WEBP supported"
          />
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto grid grid-cols-1 lg:grid-cols-3 gap-8 animate-slide-up">
      {/* Controls Sidebar */}
      <div className="lg:col-span-1 space-y-6">
        <div className="bg-surface p-6 rounded-2xl border border-zinc-800 space-y-6">
          <div className={`flex flex-col sm:flex-row items-center justify-between gap-4 ${isMobile ? 'text-center' : ''}`}>
            <h3 className="text-lg font-semibold truncate max-w-[200px] sm:max-w-none" title={file.file.name}>{file.file.name}</h3>
            <button onClick={handleReset} className={`text-xs text-red-400 hover:underline flex items-center gap-1 ${isMobile ? 'w-full justify-center' : ''}`}>
              <RefreshCcw size={12} /> New Project
            </button>
          </div>

          <div className="space-y-4">
            <ApiKeyInput
              serviceName="Gemini"
              localStorageKey="gemini_api_key"
              onKeyChange={setApiKey}
              description="Required for AI image editing"
            />

            <div className="space-y-2">
              <label className={`text-sm font-medium text-zinc-300 flex items-center gap-2 ${isMobile ? 'justify-center' : ''}`}>
                <Wand2 size={16} className="text-purple-400" />
                Magic Prompt
              </label>
              <textarea
                value={prompt}
                onChange={(e) => setPrompt((e.target as HTMLTextAreaElement).value)}
                placeholder='e.g., "Add a retro filter", "Make the sky purple", "Remove the person in background"'
                className={`w-full bg-zinc-900 border border-zinc-700 rounded-xl p-4 text-sm text-zinc-200 outline-none focus:ring-2 focus:ring-purple-500 min-h-[120px] resize-none placeholder:text-zinc-600 transition-all ${isMobile ? 'text-center' : ''}`}
                disabled={isProcessing}
              />
            </div>

            {error && (
              <div className="p-3 bg-red-500/10 border border-red-500/20 rounded-xl flex items-start gap-3 text-red-400 text-sm">
                <AlertCircle size={16} className="mt-0.5 shrink-0" />
                <p>{error}</p>
              </div>
            )}

            <Button
              className="w-full bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500 border-none shadow-lg shadow-purple-500/20"
              onClick={handleGenerate}
              isLoading={isProcessing}
              disabled={!prompt.trim() || isProcessing || !apiKey}
            >
              {isProcessing ? 'Generating...' : 'Generate Edit'}
            </Button>

            {resultImage && (
              <Button
                variant="secondary"
                className="w-full"
                onClick={() => {
                  const link = document.createElement('a');
                  link.href = resultImage;
                  link.download = `magic-edited-${file.file.name}`;
                  link.click();
                }}
              >
                <Download size={18} className="mr-2" /> Download Result
              </Button>
            )}
          </div>
        </div>

        <div className="bg-surface p-6 rounded-2xl border border-zinc-800">
          <h4 className="font-semibold text-zinc-200 mb-2 flex items-center gap-2">
            <Sparkles size={16} className="text-yellow-400" /> Tips
          </h4>
          <ul className="text-sm text-zinc-400 list-disc list-inside space-y-1">
            <li>Be specific about what you want to change.</li>
            <li>Mention styles (e.g., "watercolor style", "cyberpunk").</li>
            <li>You can ask to add or remove objects.</li>
          </ul>
        </div>
      </div>

      {/* Preview Area */}
      <div className="lg:col-span-2">
        <div className="bg-surface rounded-3xl p-2 border border-zinc-800 h-[600px] relative select-none shadow-2xl overflow-hidden group">
          <div className="relative w-full h-full rounded-2xl overflow-hidden bg-[url('https://www.transparenttextures.com/patterns/checkerboard.png')] flex items-center justify-center bg-black/50">

            {/* Image Rendering */}
            {resultImage ? (
              // Comparison View
              <div className="relative w-full h-full">
                {/* Result Image (Bottom/Right Layer) - Full Width */}
                <img
                  src={resultImage}
                  alt="Edited"
                  className="absolute inset-0 w-full h-full object-contain pointer-events-none"
                />

                {/* Original Image (Top/Left Layer) - Clipped */}
                <img
                  src={file.previewUrl}
                  alt="Original"
                  className="absolute inset-0 w-full h-full object-contain pointer-events-none"
                  style={{ clipPath: `inset(0 ${100 - sliderPosition}% 0 0)` }}
                />

                {/* Labels */}
                <div className="absolute top-4 left-4 bg-black/60 backdrop-blur text-white text-xs px-2 py-1 rounded border border-white/10 font-bold pointer-events-none">
                  Original
                </div>
                <div className="absolute top-4 right-4 bg-purple-600/90 backdrop-blur text-white text-xs px-2 py-1 rounded border border-white/10 font-bold shadow-lg shadow-purple-500/20 pointer-events-none">
                  Magic Edit
                </div>

                {/* Slider Handle & Line */}
                <div
                  className="absolute inset-y-0"
                  style={{ left: `${sliderPosition}%` }}
                >
                  <div className="absolute inset-y-0 -left-px w-0.5 bg-white shadow-[0_0_15px_rgba(0,0,0,0.5)]"></div>
                  <div className="absolute top-1/2 -translate-y-1/2 -translate-x-1/2 w-8 h-8 bg-white rounded-full flex items-center justify-center shadow-lg -ml-0.5 text-purple-600">
                    <Sliders size={16} className="rotate-90" />
                  </div>
                </div>

                {/* Invisible Range Input */}
                <input
                  type="range"
                  min="0"
                  max="100"
                  value={sliderPosition}
                  onChange={(e) => setSliderPosition(parseInt((e.target as HTMLInputElement).value))}
                  className="absolute inset-0 w-full h-full opacity-0 cursor-ew-resize z-20"
                />
              </div>
            ) : (
              // Single Preview View
              <div className="relative w-full h-full">
                <img
                  src={file.previewUrl}
                  alt="Original"
                  className="w-full h-full object-contain"
                />
                {isProcessing && (
                  <div className="absolute inset-0 bg-black/60 backdrop-blur-sm flex flex-col items-center justify-center z-10 animate-fade-in">
                    <div className="w-16 h-16 relative">
                      <div className="absolute inset-0 border-4 border-zinc-700 rounded-full"></div>
                      <div className="absolute inset-0 border-4 border-purple-500 border-t-transparent rounded-full animate-spin"></div>
                    </div>
                    <p className="text-white font-bold mt-4 text-lg">Thinking...</p>
                    <p className="text-purple-300 text-sm">Gemini is applying your changes</p>
                  </div>
                )}
                <div className="absolute top-4 left-4 bg-black/60 backdrop-blur text-white text-xs px-2 py-1 rounded border border-white/10 font-bold">
                  Original
                </div>
              </div>
            )}
          </div>
        </div>

        {resultImage && (
          <p className="text-center text-zinc-500 text-sm mt-4 animate-fade-in">
            Drag the slider to compare original vs edited version
          </p>
        )}
      </div>
    </div>
  );
};